from typing import List, Optional, Protocol

from app.models.schemas import (
  AuditLogEntry,
  Candidate,
  InterviewMessage,
  InterviewSession,
  ReviewerNote,
  Scorecard,
)


class CandidateRepository(Protocol):
  def create(self, candidate: Candidate) -> Candidate: ...

  def get(self, candidate_id: str) -> Optional[Candidate]: ...

  def list_all(self) -> List[Candidate]: ...


class InterviewRepository(Protocol):
  def create_session(self, session: InterviewSession) -> InterviewSession: ...

  def get_session(self, session_id: str) -> Optional[InterviewSession]: ...

  def update_session(self, session: InterviewSession) -> InterviewSession: ...

  def list_sessions_for_candidate(self, candidate_id: str) -> List[InterviewSession]: ...

  def list_sessions(self) -> List[InterviewSession]: ...

  def append_message(self, message: InterviewMessage) -> InterviewMessage: ...

  def list_messages(self, session_id: str) -> List[InterviewMessage]: ...


class ScorecardRepository(Protocol):
  def upsert(self, scorecard: Scorecard) -> Scorecard: ...

  def get_for_session(self, session_id: str) -> Optional[Scorecard]: ...


class ReviewerNoteRepository(Protocol):
  def list_for_candidate(self, candidate_id: str) -> List[ReviewerNote]: ...

  def create(self, note: ReviewerNote) -> ReviewerNote: ...


class AuditLogRepository(Protocol):
  def append(self, entry: AuditLogEntry) -> AuditLogEntry: ...

  def list_recent(self, limit: int = 100) -> List[AuditLogEntry]: ...
